name: Python application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your requirements file if applicable

      - name: Lint with flake8
        run: |
          flake8 app.py test_app.py --count --exit-zero --max-line-length=127 --statistics
          # Adjust the linting command based on your structure

      - name: Test with pytest
        run: |
          pytest test_app.py  # Run tests using pytest against test_app.py
